### ISSUE TITLE
[Question] Can we set a custom captcha text?

### ISSUE THREAD

**Issue by 91DarioDev** [J-Rios/multicolor-captcha-generator#16]
How can we choose the text to use for the captcha ?

**Comment by J-Rios** [comment]
Hello,

Do you mean the font used in the images?

Current library implementation loads all fonts that are placed inside the "multicolorcaptcha/fonts" directory at object instantiation. Then, when a captcha image generation is requested, any of this fonts are randomly selected and used.

**Comment by 91DarioDev** [comment]
Sorry I meant this: I want to tell the library which text the image should contains. Example: I want the pic to have "12345" inside.

in the readme it seems like that the code inside the captcha is random and cannot be chosen

**Comment by J-Rios** [comment]
Correct, the captcha text/numbers are randomly generated and currently there is no support for generating captchas from custom text/number request.

If you want feel free to contribute into the project adding that support, otherwise we can set this issue as a Request (instead of a question) and wait if someone wants to add that functionality :)
